/** Danh sách ngân hàng phổ biến tại Việt Nam — dùng cho dropdown gợi ý (datalist) */
export const VIETNAM_BANKS = [
  "Vietcombank",
  "VietinBank",
  "BIDV",
  "Agribank",
  "Techcombank",
  "MB Bank (Quân đội)",
  "ACB",
  "VPBank",
  "Sacombank",
  "TPBank",
  "SHB",
  "HDBank",
  "VIB",
  "SeABank",
  "OCB (Phương Đông)",
  "MSB (Hàng Hải)",
  "Eximbank",
  "LienVietPostBank",
  "Nam A Bank",
  "Bac A Bank",
  "PVcomBank",
  "ABBANK",
  "SCB",
  "BaoViet Bank",
  "Viet Capital Bank (Bản Việt)",
  "Kien Long Bank",
  "PG Bank",
  "SaigonBank",
  "Public Bank Vietnam",
  "CIMB Vietnam",
  "Standard Chartered Vietnam",
  "HSBC Vietnam",
  "Shinhan Bank Vietnam",
  "Woori Bank Vietnam",
  "UOB Vietnam",
  "CAKE by VPBank",
  "Timo",
  "Ngân hàng Nhà nước (Kho bạc)",
];
